services:
  - type: web
    name: co-nowcast-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && python backend/scripts/convert_insat_to_hdf5.py"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
